<?php
  require "conexion_bd.php";
  $msg="";
  if(count($_POST)>0){
	  $table=$_POST['table'];
	  $fields=$_POST['fields'];
	  $num_fields=$_POST['num_fields'];
	  $conds=$_POST['conds'];
	  $opcion1=$_POST['op1'];
	  $opcion2=$_POST['op2'];
	  if(isset($table) && isset($fields) && isset($num_fields) && isset($conds) && isset($opcion1) && isset($opcion2)){
		  if(validar_conexion()){
			  if(count($conds)==2){
				  if($table=="trabajador"){
					 $temp_fields=array("CI_trabaj");
					 for($i=0;$i<$num_fields;$i++){
						 $temp_fields[]=$fields[$i];
					 }
					 $num_fields=$num_fields+1;
		             $fields=$temp_fields;
	              }
				  $data=get_data($table,$fields,$num_fields,$conds[0],$conds[1]);
				  if(count($data)>0){
					  $msg=":";
					  for($i=0;$i<count($data);$i++){
						 $row="";
						 $ignored_row=false;
						 for($j=0;$j<count($data[$i]);$j++){
							 $valid_column=true;
							 if($table=="trabajador"){
								 if($j==0){
									 if($data[$i][$j]=="000000"){
										 $ignored_row=true;
										 $j=count($data[$i]);
									 }
									 $valid_column=false;
								 } 
							 }
							 if($valid_column){
							    if($j<count($data[$i])-1){
								    $row=$row.$data[$i][$j].",";
							    }
							    else{
								    $row=$row.$data[$i][$j];
							    }
							 }
						 }
						 if($row!=""){
							 $msg=$msg.$row;
						 }
						 if($i<count($data)-1 &&$ignored_row==false){
							 $msg=$msg.";"; 
						 }
					  }
					  $msg=$msg."|".$opcion1.",".$opcion2;  
				  }
			  }  
		  }
	  } 
  }
  echo $msg;
?>